Target:
  - Drutiny\Target\DrushTarget
  - Drutiny\Target\TargetNone
Command:
  - Drutiny\Command\AuditGenerateCommand
  - Drutiny\Command\AuditInfoCommand
  - Drutiny\Command\AuditListCommand
  - Drutiny\Command\AuditRunCommand
  - Drutiny\Command\AuthenticateCommand
  - Drutiny\Command\PolicyAuditCommand
  - Drutiny\Command\PolicyInfoCommand
  - Drutiny\Command\PolicyListCommand
  - Drutiny\Command\ProfileGenerateCommand
  - Drutiny\Command\ProfileInfoCommand
  - Drutiny\Command\ProfileListCommand
  - Drutiny\Command\ProfileRunCommand
Template:
  - src/Report/templates/html
  - src/Report/templates/markdown
DomainList:
  YamlFile: Drutiny\DomainList\DomainListYamlFile
Format:
  html: Drutiny\Report\Format\HTML
  json: Drutiny\Report\Format\JSON
  markdown: Drutiny\Report\Format\Markdown
  terminal: Drutiny\Report\Format\Terminal
  console: Drutiny\Report\Format\Console
Driver:
  drush: Drutiny\Driver\DrushRouter::create
PolicySource:
  - Drutiny\PolicySource\DrutinyGitHubIO
  - Drutiny\PolicySource\LocalFs
