Target:
  - Drutiny\Target\DrushTarget
  - Drutiny\Target\TargetNone
Command:
  - Drutiny\Command\AuditGenerateCommand
  - Drutiny\Command\AuditInfoCommand
  - Drutiny\Command\AuditListCommand
  - Drutiny\Command\AuditRunCommand
  - Drutiny\Command\AuthenticateCommand
  - Drutiny\Command\PolicyAuditCommand
  - Drutiny\Command\PolicyInfoCommand
  - Drutiny\Command\PolicyListCommand
  - Drutiny\Command\ProfileGenerateCommand
  - Drutiny\Command\ProfileInfoCommand
  - Drutiny\Command\ProfileListCommand
  - Drutiny\Command\ProfileRunCommand
Template:
  - src/Report/templates
