site_name: Drutiny
site_dir: docs_html
repo_url: 'https://github.com/drutiny/drutiny'
site_description: 'This is a generic Drupal site auditing and optional remediation tool.'
theme: material
google_analytics:
    - UA-116046012-1
    - drutiny.github.io
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js'
    - js/highlight.js
extra_css:
    - css/tweaks.css
    - 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/atom-one-light.min.css'
pages:
    -
        Home: index.md
    -
        Usage:
            -
                Reports: reports.md
            -
                Plugins: plugins.md
            -
                Contributing: CONTRIBUTING.md
    -
        'API Documentation':
            -
                Audit: audits.md
            -
                Sandbox: sandbox.md
            -
                Policy: policy.md
            -
                Profile: profiles.md
    -
        'Policy Library':
            -
                Overview: policy-library.md
            -
                drutiny/drutiny: policies/drutiny-drutiny.md
            -
                drutiny/acquia: policies/drutiny-acquia.md
            -
                drutiny/plugin-drupal-8: policies/drutiny-plugin-drupal-8.md
            -
                drutiny/plugin-drupal-7: policies/drutiny-plugin-drupal-7.md
            -
                drutiny/plugin-distro-common: policies/drutiny-plugin-distro-common.md
            -
                drutiny/cloudflare: policies/drutiny-cloudflare.md
            -
                drutiny/http: policies/drutiny-http.md
    -
        'Audit Library':
            -
                Drutiny\Audit: audits/DrutinyAudit.md
            -
                Drutiny\Audit\Drupal: audits/DrutinyAuditDrupal.md
            -
                Drutiny\Audit\Filesystem: audits/DrutinyAuditFilesystem.md
            -
                Drutiny\Audit\Database: audits/DrutinyAuditDatabase.md
            -
                Drutiny\Audit\Apache: audits/DrutinyAuditApache.md
            -
                Drutiny\Acquia\Audit: audits/DrutinyAcquiaAudit.md
            -
                Drutiny\Plugin\Drupal8\Audit: audits/DrutinyPluginDrupal8Audit.md
            -
                Drutiny\Http\Audit: audits/DrutinyHttpAudit.md
            -
                Drutiny\Plugin\Drupal7\Audit: audits/DrutinyPluginDrupal7Audit.md
            -
                Drutiny\Plugin\Drupal7\Audit\Security: audits/DrutinyPluginDrupal7AuditSecurity.md
            -
                Drutiny\Cloudflare\Audit: audits/DrutinyCloudflareAudit.md
            -
                Drutiny\SumoLogic\Audit: audits/DrutinySumoLogicAudit.md
            -
                Drutiny\Audit\DNS: audits/DrutinyAuditDNS.md
