site_name: Drutiny
site_dir: docs_html
repo_url: 'https://github.com/drutiny/drutiny'
site_description: 'This is a generic Drupal site auditing and optional remediation tool.'
theme: material
google_analytics:
    - UA-116046012-1
    - drutiny.github.io
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js'
    - js/highlight.js
extra_css:
    - css/tweaks.css
    - 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/atom-one-light.min.css'
pages:
    -
        Home: index.md
    -
        Usage:
            -
                Getting Started: getting-started.md
            -
                Reports: reports.md
            -
                Plugins: plugins.md
            -
                Contributing: CONTRIBUTING.md
    -
        'API Documentation':
            -
                Audit: audits.md
            -
                Sandbox: sandbox.md
            -
                Policy: policy.md
            -
                Profile: profiles.md
            -
                Config: config.md
            -
                'Credential Manager': creds.md
            -
                'Domain Provider': domains.md
    -
        'Policy Library':
            -
                Overview: policy-library.md
            -
                drutiny/drutiny: policies/drutiny-drutiny.md
    -
        'Audit Library':
            -
                General: audits/DrutinyAudit.md
            -
                Apache: audits/DrutinyAuditApache.md
            -
                DNS: audits/DrutinyAuditDNS.md
            -
                Database: audits/DrutinyAuditDatabase.md
            -
                Drupal: audits/DrutinyAuditDrupal.md
            -
                Filesystem: audits/DrutinyAuditFilesystem.md
