metadata :
  machine_name: 'default'
  title : 'Site audit'
checks :
  \SiteAudit\Drush\ModulePHP : {}
  \SiteAudit\Drush\ModuleStatistics : {}
  \SiteAudit\Drush\ModuleSyslog : {}
  \SiteAudit\Drush\PreprocessCSS : {}
  \SiteAudit\Drush\PreprocessJS : {}
  \SiteAudit\Drush\PageCacheMaximumAge :
    cache : 300
  \SiteAudit\Drush\UpdateDBStatus: {}
  \SiteAudit\Ssh\HtaccessRedirects :
    max_redirects : 8
